name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

permissions:
    contents: write
    pull-requests: write

jobs:
    backend:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./backend

        steps:
            - uses: actions/checkout@v4
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: "1.24"

            - name: Cache Go modules
              uses: actions/cache@v4
              with:
                  path: ~/go/pkg/mod
                  key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
                  restore-keys: |
                      ${{ runner.os }}-go-

            - name: Install dependencies
              run: go mod download

            - name: Check for outdated dependencies
              run: go mod tidy

            - name: Install cyclonedx-gomod
              run: go install github.com/CycloneDX/cyclonedx-gomod/cmd/cyclonedx-gomod@latest

            - name: Generate Backend SBOM
              run: |
                  go mod tidy
                  cyclonedx-gomod mod -json -licenses -assert-licenses -output sbom.json

            - name: Install golangci-lint
              run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

            - name: Run golangci-lint
              run: golangci-lint run

            - name: Run tests with coverage
              run: go test -v -coverprofile=coverage.out ./...

            - name: Build
              run: go build -v ./...

            - name: Upload build artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: backend-binary
                  path: ./backend
                  retention-days: 5

            - name: Commit and push Backend SBOM if changed
              if: github.event_name == 'push'
              run: |
                  cd ${{ github.workspace }}
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  git add backend/sbom.json
                  if ! git diff --quiet && ! git diff --staged --quiet; then
                      git commit -m "ci: update backend SBOM"
                      git push
                  fi

    frontend:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./frontend

        steps:
            - uses: actions/checkout@v4
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "22"

            - name: Cache npm dependencies
              uses: actions/cache@v4
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-

            - name: Install dependencies
              run: npm ci

            - name: Generate Frontend SBOM
              run: |
                  npm install
                  npx @cyclonedx/cyclonedx-npm --output-file public/sbom.json

            - name: Run linter
              run: npm run lint

            - name: Run tests with coverage
              run: npm test -- --coverage

            - name: Build
              run: npm run build

            - name: Upload build artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: frontend-build
                  path: ./frontend/dist
                  retention-days: 5

            - name: Commit and push Frontend SBOM if changed
              if: github.event_name == 'push'
              run: |
                  cd ${{ github.workspace }}
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  git add frontend/public/sbom.json
                  if ! git diff --quiet && ! git diff --staged --quiet; then
                      git commit -m "ci: update frontend SBOM"
                      git push
                  fi
